Adding webdriver.js-example-project
dequelabs/axe-devtools-html-api-examples pull request #19
Opened 2022-05-04 14:09 UTC by ankit-dq

2022-05-04 21:44 UTC, michael-siek requested changes

2022-05-04 21:44 UTC, michael-siek commented on Node/webdriver.js_vanilla/tests/example.spec.js
> +const async_hooks = require('async_hooks');
```suggestion
```

2022-05-04 21:44 UTC, michael-siek commented on Node/webdriver.js_vanilla/tests/example.spec.js
> +// var driver = new WebDriver.Builder().forBrowser('chrome').build();
```suggestion
```

2022-05-04 21:44 UTC, michael-siek commented on Node/webdriver.js_vanilla/tests/example.spec.js
> +exampleTest()
This is an async function and needs to be resolved via promise/await

2022-05-04 21:44 UTC, michael-siek commented on Node/webdriver.js_vanilla/tests/example.spec.js
> +
```suggestion
```

2022-05-04 21:44 UTC, michael-siek commented on Node/webdriver.js_vanilla/package.json
> +  "author": "",
```suggestion
```

2022-05-04 21:44 UTC, michael-siek commented on Node/webdriver.js_vanilla/package.json
> +  "description": "",
We should add a description

2022-05-04 21:44 UTC, michael-siek commented on Node/webdriver.js_vanilla/package.json
> +  "dependencies": {
These should all be devdeps

2022-05-09 14:50 UTC, AdnoC approved these changes

2022-05-10 09:49 UTC, merged