Added python generic example project
dequelabs/axe-devtools-html-api-examples pull request #25
Opened 2022-06-14 13:49 UTC by ankit-dq

2022-06-23 14:38 UTC, jthickens submitted a review, later dismissed

2022-06-23 14:38 UTC, jthickens commented on Python/python_generic/README.md
> +Python 3 (does not support python 2) along with the virtual environment (venv or pyenv)
```suggestion
Python 3 (does not support python 2) along with the virtual environment (venv or pyenv).
```

2022-06-23 14:38 UTC, jthickens commented on Python/python_generic/README.md
> +Download the respective [Binary reporter](https://docs.deque.com/devtools-html/4.0.0/en/downloads#binary-reporter) and place it in the **_resources_** directory.
```suggestion
Download the respective [Binary reporter](https://docs.deque.com/devtools-html/4.0.0/en/downloads#binary-reporter) for your operating system and place it in the **_resources_** directory.
```

2022-06-23 14:38 UTC, jthickens commented on Python/python_generic/README.md
> +
```suggestion
```

2022-06-23 14:38 UTC, jthickens commented on Python/python_generic/README.md
> +The tests generate results in the **_a11y-results_** directory.
```suggestion
The tests generate results in the **_a11y-results_** directory if you have installed the reporter binary. If you have not completed this step, only JSON reports will be created.
```

2022-06-23 14:38 UTC, jthickens commented on Python/python_generic/README.md
> +Python 3 (does not support python 2) along with the virtual environment (venv or pyenv)
```suggestion
Python 3 (does not support Python 2) along with the virtual environment (venv or pyenv)
```

2022-06-29 02:22 UTC, jthickens requested changes

2022-06-29 02:22 UTC, jthickens commented on Python/python_generic/README.md
> +cd Python/python_generic
^^

2022-06-29 06:14 UTC, ankit-dq commented on Python/python_generic/README.md
> +cd Python/python_generic
Updated the dir name to python_selenium

2022-07-06 17:47 UTC, jthickens approved these changes
@AdnoC should review the python test files, but everything else lgtm

2022-07-12 03:51 UTC, AdnoC approved these changes

2022-07-12 06:51 UTC, merged