Adding files to pytest example project
dequelabs/axe-devtools-html-api-examples pull request #30
Opened 2022-06-17 14:05 UTC by ankit-dq

2022-06-23 14:46 UTC, jthickens submitted a review, later dismissed

2022-06-29 02:25 UTC, jthickens approved these changes

2022-06-29 02:25 UTC, jthickens commented on Python/pytest/resources/.txt
> +Download the respective [Binary reporter](https://docs.deque.com/devtools-html/4.0.0/en/downloads#binary-reporter) and place it in this directory.
```suggestion
Download the respective [Binary reporter](https://docs.deque.com/devtools-html/4.0.0/en/downloads#binary-reporter) for your operating system and place it in this directory.
```

2022-06-29 02:25 UTC, jthickens commented on Python/pytest/README.md
> +Python 3 (does not support Python 2) along with the virtual environment (venv or pyenv)
```suggestion
Python 3 (does not support Python 2) along with the virtual environment (venv or pyenv).
```

2022-06-29 02:33 UTC, jthickens requested changes
see comments

2022-07-06 19:23 UTC, jthickens approved these changes
lgtm - python should be reviewed by @AdnoC

2022-07-12 03:50 UTC, AdnoC approved these changes

2022-07-12 06:50 UTC, merged