Adding files to java-hamcrest example project
dequelabs/axe-devtools-html-api-examples pull request #35
Opened 2022-07-04 13:39 UTC by ankit-dq

2022-07-05 15:25 UTC, Zidious requested changes
Minor changes

2022-07-05 15:25 UTC, Zidious commented on Java/hamcrest/src/test/java/deque/exampleTest.java
> +    }
```suggestion
    private String reporter = new File("src/test/resources/reporter-cli-macos").getAbsolutePath();
    private AxeReportingOptions _reportOptions;
    private WebDriver driver;
    private AxeDriver axedriver;
    private AxeSelenium axeSelenium;
    private String Logger;
    private String Destination;

    @Before
    public void init() {
        _reportOptions = new AxeReportingOptions();
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        axedriver = new AxeDriver(driver);
        axeSelenium = new AxeSelenium();
        AxeConfiguration.configure()
                .testSuiteName("Test")
                .outputDirectory("axe-json-reports/");
        Logger =  new File("axe-json-reports/").getAbsolutePath();
        Destination =  new File("a11y-results/").getAbsolutePath();

    }
```

We don't need to use static variables here, we can use Junit's `@Before` which will run before each test. 

We could use JUnit 5 - which has `@BeforeAll` which will run only once (before all tests) and remove the use of `static`

2022-07-05 15:25 UTC, Zidious commented on Java/hamcrest/src/test/java/deque/exampleTest.java
> +        catch(Exception e){System.out.println(e);}
nit - 
```suggestion
        catch(Exception e) {
        	e.printStackTrace();
        }
```

2022-07-05 15:25 UTC, Zidious commented on Java/hamcrest/pom.xml
> +        </plugin>
Are we using most of these plugins?

2022-07-08 15:52 UTC, Zidious submitted a review, later dismissed
One small thing, LGTM otherwise. Will need @jthickens to review README

2022-07-08 15:52 UTC, Zidious commented on Java/hamcrest/pom.xml
> +  <url>http://www.example.com</url>
URL missing here

2022-07-12 02:34 UTC, Zidious approved these changes
LGTM - @jthickens will need to review the README

2022-07-12 17:34 UTC, jthickens submitted a review, later dismissed

2022-07-12 17:34 UTC, jthickens commented on Java/hamcrest/README.md
> +- Selenium WebDriver
what does selenium webdriver mean here, specifically? A chromedriver binary? Something else?

2022-07-12 17:34 UTC, jthickens commented on Java/hamcrest/pom.xml
> +      <groupId>com.deque.html.axe-devtools</groupId>
where's the section to add auth information?

2022-07-18 19:12 UTC, michael-siek submitted a review, later dismissed

2022-07-18 19:12 UTC, michael-siek commented on Java/hamcrest/README.md
> +mvn compile
```suggestion
mvn clean install
```

2022-07-19 13:52 UTC, merged